# Generated by Django 3.1 on 2020-08-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loginforms',
            new_name='loginform',
        ),
    ]
